/**
 * DEMO CONTENT — for design preview only.
 *
 * These stories are fictional placeholders. They deliberately avoid named
 * individuals, companies and specific incidents, and every one is flagged
 * `isDemo` so the UI labels it. Replace with Supabase content before launch.
 */
import type { Article, ArticleBlock, ArticleFormat, MediaImage } from "@/lib/types";
import { desks, type DeskId } from "./authors";

/** Anchor demo timestamps to "now" (rounded to 5 min) so the preview always looks current. */
const NOW = Math.floor(Date.now() / 300_000) * 300_000;
const minutesAgo = (m: number) => new Date(NOW - m * 60_000).toISOString();

export function demoImage(name: string, alt: string, caption?: string): MediaImage {
  return {
    src: `/demo/${name}.svg`,
    alt,
    width: 1600,
    height: 900,
    caption: caption ?? "Placeholder illustration for demo content.",
    credit: "Demo illustration",
  };
}

function demoBody(location: string | undefined, dek: string, deskName: string, format: ArticleFormat): ArticleBlock[] {
  const place = location ? `${location.toUpperCase()}: ` : "";
  const blocks: ArticleBlock[] = [
    {
      type: "note",
      text: "This is demonstration content created to preview the Anjaan Khabar reading experience. It does not report a real event.",
    },
    { type: "p", text: `${place}${dek}` },
    {
      type: "p",
      text: "In a published Anjaan Khabar report, the opening paragraphs establish what happened, where and when, and who is affected — in plain language, with the most important facts first. Readers should be able to stop after two paragraphs and still understand the story.",
    },
    { type: "h2", text: format === "explainer" ? "The short version" : "What we know" },
    {
      type: "list",
      items: [
        "Verified facts appear here, each attributed to a named source, official record or document.",
        "Statements from officials and those affected are quoted directly and dated.",
        "Anything not yet confirmed is clearly labelled as unconfirmed.",
      ],
    },
    {
      type: "p",
      text: `Reporting for stories like this is led by the ${deskName}, with editors checking every figure and quotation before publication. Where a claim cannot be independently verified, the story says so.`,
    },
    {
      type: "quote",
      text: "Every claim in a story should be something we can show the reader how we know.",
      cite: "Anjaan Khabar editorial standards",
    },
    { type: "h2", text: "Why it matters" },
    {
      type: "p",
      text: "This section connects the development to readers' daily lives — travel, money, safety, schooling or public services — and explains the local context that national coverage often misses.",
    },
    {
      type: "p",
      text: "Where the story is still unfolding, the article is updated with a clear timestamp, and substantive changes are noted at the end of the piece in line with our corrections policy.",
    },
    { type: "h2", text: "What happens next" },
    {
      type: "p",
      text: "The closing section sets out upcoming dates, decisions or follow-ups, so readers know what to watch for. Readers with information relevant to this story can reach the newsroom on WhatsApp.",
    },
  ];
  return blocks;
}

interface DemoInput {
  slug: string;
  title: string;
  dek: string;
  section: string;
  locality?: string;
  topics?: string[];
  tags?: string[];
  location?: string;
  desk: DeskId;
  mins: number;
  updatedMins?: number;
  image: [name: string, alt: string, caption?: string];
  priority: number;
  format?: ArticleFormat;
  takeaways?: string[];
  isBreaking?: boolean;
  isDeveloping?: boolean;
}

let counter = 0;
function article(i: DemoInput): Article {
  const format = i.format ?? "news";
  const author = desks[i.desk];
  counter += 1;
  return {
    id: `demo-${counter.toString().padStart(3, "0")}`,
    slug: i.slug,
    title: i.title,
    dek: i.dek,
    section: i.section,
    locality: i.locality,
    topics: i.topics ?? [],
    tags: i.tags ?? [],
    location: i.location,
    author,
    publishedAt: minutesAgo(i.mins),
    updatedAt: i.updatedMins !== undefined ? minutesAgo(i.updatedMins) : undefined,
    image: demoImage(...i.image),
    body: demoBody(i.location, i.dek, author.name, format),
    keyTakeaways: i.takeaways,
    format,
    priority: i.priority,
    isBreaking: i.isBreaking,
    isDeveloping: i.isDeveloping,
    isDemo: true,
  };
}

export const demoArticles: Article[] = [
  // ---------------------------------------------------------------- JHARKHAND (state-wide)
  article({
    slug: "districts-asked-to-map-flood-prone-villages-before-next-monsoon",
    title: "Jharkhand monsoon review: districts asked to map flood-prone villages before next season",
    dek: "A state-level review asks every district to list vulnerable settlements, drainage bottlenecks and relief shelters well ahead of the next monsoon.",
    section: "jharkhand",
    topics: ["politics"],
    tags: ["Monsoon", "Disaster preparedness", "Governance"],
    location: "Ranchi",
    desk: "jharkhand",
    mins: 38,
    updatedMins: 9,
    image: ["jharkhand-monsoon", "Illustration of rain over green hills", "Placeholder illustration: monsoon over the Chotanagpur plateau."],
    priority: 98,
    isDeveloping: true,
    takeaways: [
      "Every district is asked to prepare a village-level flood vulnerability list.",
      "Drainage bottlenecks and relief shelters are to be mapped in the same exercise.",
      "Districts will report progress at a follow-up review.",
    ],
  }),
  article({
    slug: "mobile-clinics-expand-to-remote-blocks",
    title: "Mobile clinics to reach more remote blocks across Jharkhand",
    dek: "Health teams plan more frequent visits to villages far from primary health centres, with a focus on maternal and child care.",
    section: "jharkhand",
    topics: ["health"],
    tags: ["Public health", "Rural healthcare"],
    location: "Ranchi",
    desk: "jharkhand",
    mins: 150,
    image: ["jharkhand-health", "Abstract illustration representing healthcare"],
    priority: 80,
  }),
  article({
    slug: "rail-commuters-seek-more-stoppages-on-intercity-routes",
    title: "Rail commuters in Jharkhand ask for more stoppages on busy intercity routes",
    dek: "Passenger groups from smaller towns say daily travel for work and college depends on a handful of trains that skip their stations.",
    section: "jharkhand",
    tags: ["Railways", "Commuting"],
    location: "Dhanbad",
    desk: "jharkhand",
    mins: 260,
    image: ["jharkhand-rail", "Illustration of railway tracks converging"],
    priority: 72,
  }),
  article({
    slug: "tribal-craft-cooperatives-look-online-for-buyers",
    title: "Jharkhand's craft cooperatives look online for new buyers",
    dek: "Artisan groups working in bamboo, dokra and textiles are experimenting with online orders — and learning the logistics the hard way.",
    section: "jharkhand",
    topics: ["business"],
    tags: ["Handicrafts", "Livelihoods"],
    location: "Khunti",
    desk: "jharkhand",
    mins: 540,
    image: ["odisha-culture", "Abstract illustration of patterns and colour"],
    priority: 64,
  }),
  // ---------------------------------------------------------------- JAMSHEDPUR
  article({
    slug: "subarnarekha-riverfront-walkway-residents-weigh-in",
    title: "Subarnarekha riverfront: residents weigh in on a proposed walkway and cycle lanes",
    dek: "Neighbourhood groups want safer access to the river. Shopkeepers want to know what it means for parking. Here is what each side is asking for.",
    section: "jharkhand",
    locality: "jamshedpur",
    tags: ["Urban planning", "Public spaces"],
    location: "Jamshedpur",
    desk: "jamshedpur",
    mins: 95,
    image: ["jamshedpur-river", "Illustration of a river winding between hills"],
    priority: 91,
    takeaways: [
      "Residents' groups are asking for a continuous riverside walkway.",
      "Traders want clarity on parking and delivery access.",
      "Public feedback is expected to shape the final design.",
    ],
  }),
  article({
    slug: "festival-traffic-plan-for-bistupur-and-sakchi-markets",
    title: "Jamshedpur draws up festival-season traffic plan for Bistupur and Sakchi markets",
    dek: "One-way stretches, temporary parking zones and restricted hours for heavy vehicles are among the measures being considered.",
    section: "jharkhand",
    locality: "jamshedpur",
    tags: ["Traffic", "Festivals"],
    location: "Jamshedpur",
    desk: "jamshedpur",
    mins: 22,
    image: ["jamshedpur-road", "Illustration of a city road at dusk"],
    priority: 86,
    isBreaking: true,
  }),
  article({
    slug: "water-supply-schedule-revised-during-pipeline-maintenance",
    title: "Water supply schedule revised in parts of Jamshedpur during pipeline maintenance",
    dek: "Affected neighbourhoods will receive water at changed hours for several days. Here is how to check whether your area is included.",
    section: "jharkhand",
    locality: "jamshedpur",
    tags: ["Civic services", "Water"],
    location: "Jamshedpur",
    desk: "jamshedpur",
    mins: 210,
    image: ["jamshedpur-skyline", "Illustration of a city skyline at night"],
    priority: 70,
  }),
  article({
    slug: "industrial-safety-week-joint-drills",
    title: "Industrial safety week: workers and managements hold joint drills in Jamshedpur",
    dek: "Fire, evacuation and first-aid drills across industrial units aim to test response times on the shop floor.",
    section: "jharkhand",
    locality: "jamshedpur",
    topics: ["business"],
    tags: ["Workplace safety", "Industry"],
    location: "Jamshedpur",
    desk: "jamshedpur",
    mins: 400,
    image: ["jamshedpur-industry", "Illustration of industrial chimneys"],
    priority: 66,
  }),
  article({
    slug: "colleges-open-applications-for-evening-skill-courses",
    title: "Jamshedpur colleges open applications for evening skill courses",
    dek: "Short courses in accounting software, electrical work and data entry are aimed at working adults and recent school leavers.",
    section: "jharkhand",
    locality: "jamshedpur",
    topics: ["education"],
    tags: ["Skills", "Higher education"],
    location: "Jamshedpur",
    desk: "jamshedpur",
    mins: 720,
    image: ["education-books", "Illustration of books on a shelf"],
    priority: 58,
  }),
  article({
    slug: "residents-push-for-more-green-cover-along-marine-drive",
    title: "Residents' groups push for more green cover along Marine Drive",
    dek: "Morning walkers and cyclists say shade and seating would make the stretch safer and more usable through the summer.",
    section: "jharkhand",
    locality: "jamshedpur",
    tags: ["Environment", "Public spaces"],
    location: "Jamshedpur",
    desk: "jamshedpur",
    mins: 1500,
    image: ["jharkhand-hills", "Illustration of layered green hills"],
    priority: 52,
  }),
  // ---------------------------------------------------------------- RANCHI
  article({
    slug: "traffic-study-recommends-signal-upgrades-at-busy-junctions",
    title: "Ranchi traffic study recommends signal upgrades at five busy junctions",
    dek: "The study points to long waiting times and unsafe pedestrian crossings at peak hours, and suggests timed signals and marked crossings.",
    section: "jharkhand",
    locality: "ranchi",
    tags: ["Traffic", "Road safety"],
    location: "Ranchi",
    desk: "ranchi",
    mins: 70,
    image: ["ranchi-skyline", "Illustration of a city skyline"],
    priority: 88,
    takeaways: [
      "Five junctions are identified for signal upgrades.",
      "Pedestrian crossings are a key concern at peak hours.",
      "Recommendations now go to the city's traffic authorities.",
    ],
  }),
  article({
    slug: "weekly-haats-see-early-winter-crowds",
    title: "Ranchi's weekly haats see early winter crowds as vegetable prices steady",
    dek: "Traders at the city's weekly markets say footfall has picked up, with shoppers buying in bulk ahead of the festive weeks.",
    section: "jharkhand",
    locality: "ranchi",
    topics: ["business"],
    tags: ["Markets", "Prices"],
    location: "Ranchi",
    desk: "ranchi",
    mins: 180,
    image: ["ranchi-market", "Illustration of market stalls with awnings"],
    priority: 68,
  }),
  article({
    slug: "public-library-reading-rooms-ahead-of-exam-season",
    title: "New reading rooms open in Ranchi public libraries ahead of exam season",
    dek: "Extended hours and quiet study spaces are meant to help students preparing for competitive examinations.",
    section: "jharkhand",
    locality: "ranchi",
    topics: ["education"],
    tags: ["Libraries", "Students"],
    location: "Ranchi",
    desk: "ranchi",
    mins: 330,
    image: ["jharkhand-classroom", "Illustration of books standing on a shelf"],
    priority: 62,
  }),
  article({
    slug: "forest-trails-visitor-safety-review",
    title: "Hill trails around Ranchi: visitor safety measures under review",
    dek: "Signage, marked paths and emergency contact points are being considered for popular weekend trekking spots.",
    section: "jharkhand",
    locality: "ranchi",
    tags: ["Tourism", "Safety"],
    location: "Ranchi",
    desk: "ranchi",
    mins: 900,
    image: ["ranchi-hills", "Illustration of forested hills"],
    priority: 55,
  }),
  article({
    slug: "civic-body-invites-comments-on-ward-budget",
    title: "Ranchi civic body invites public comments on ward-level budget",
    dek: "Residents can suggest priorities for roads, drains and streetlights in their wards before the budget is finalised.",
    section: "jharkhand",
    locality: "ranchi",
    topics: ["politics"],
    tags: ["Civic budget", "Participation"],
    location: "Ranchi",
    desk: "ranchi",
    mins: 1300,
    image: ["ranchi-civic", "Illustration of a public building with columns"],
    priority: 57,
  }),
  // ---------------------------------------------------------------- OTHER JHARKHAND DISTRICTS
  article({
    slug: "health-camps-focus-on-respiratory-screening",
    title: "Dhanbad health camps focus on respiratory screening for mine workers",
    dek: "Doctors say early screening can catch lung conditions before they become disabling, and urge workers to attend follow-up visits.",
    section: "jharkhand",
    locality: "dhanbad",
    topics: ["health"],
    tags: ["Occupational health", "Mining"],
    location: "Dhanbad",
    desk: "jharkhand",
    mins: 280,
    image: ["jharkhand-mining", "Illustration of an industrial landscape"],
    priority: 67,
  }),
  article({
    slug: "schools-pilot-shared-science-labs",
    title: "Bokaro schools pilot science labs shared across nearby villages",
    dek: "Students from smaller schools travel on fixed days to use equipment their own schools cannot afford.",
    section: "jharkhand",
    locality: "bokaro",
    topics: ["education"],
    tags: ["Schools", "Science education"],
    location: "Bokaro",
    desk: "jharkhand",
    mins: 620,
    image: ["education-books", "Illustration of books"],
    priority: 60,
  }),
  article({
    slug: "farmers-turn-to-drip-irrigation",
    title: "Hazaribagh farmers turn to drip irrigation ahead of the dry months",
    dek: "Vegetable growers say drip lines cut water use, but the upfront cost remains a hurdle for small landholders.",
    section: "jharkhand",
    locality: "hazaribagh",
    topics: ["business"],
    tags: ["Agriculture", "Water"],
    location: "Hazaribagh",
    desk: "jharkhand",
    mins: 840,
    image: ["jharkhand-hills", "Illustration of farmland and hills"],
    priority: 59,
  }),
  article({
    slug: "crowd-management-plan-for-pilgrimage-season",
    title: "Deoghar prepares crowd-management plan for the pilgrimage season",
    dek: "Queue systems, medical posts and traffic diversions are being planned around the town's busiest routes.",
    section: "jharkhand",
    locality: "deoghar",
    tags: ["Pilgrimage", "Public safety"],
    location: "Deoghar",
    desk: "jharkhand",
    mins: 1100,
    image: ["entertainment-stage", "Abstract illustration of light and colour"],
    priority: 61,
  }),
  article({
    slug: "rural-roads-monsoon-damage-review",
    title: "Giridih reviews monsoon damage to rural roads and sets repair timelines",
    dek: "Village roads cut off during heavy rain are to be prioritised, officials say, with repairs scheduled block by block.",
    section: "jharkhand",
    locality: "giridih",
    tags: ["Roads", "Monsoon"],
    location: "Giridih",
    desk: "jharkhand",
    mins: 1700,
    image: ["up-road", "Illustration of a road stretching to the horizon"],
    priority: 50,
  }),
  // ---------------------------------------------------------------- BIHAR
  article({
    slug: "river-towns-begin-embankment-inspections",
    title: "Bihar's river towns begin annual embankment inspections",
    dek: "Engineers walk vulnerable stretches after the monsoon to log erosion and plan repairs before the next flood season.",
    section: "bihar",
    tags: ["Floods", "Infrastructure"],
    location: "Patna",
    desk: "regional",
    mins: 120,
    image: ["bihar-river", "Illustration of a wide river"],
    priority: 76,
  }),
  article({
    slug: "district-offices-move-certificates-online",
    title: "More certificates move online at Bihar district offices",
    dek: "Residents can now apply for several common certificates without visiting a block office. Here is what changes.",
    section: "bihar",
    topics: ["technology"],
    tags: ["Public services", "Digital governance"],
    location: "Patna",
    desk: "regional",
    mins: 480,
    image: ["bihar-civic", "Illustration of a public building"],
    priority: 63,
  }),
  article({
    slug: "commuters-guide-to-city-bus-route-changes",
    title: "A commuter's guide to changing city bus routes in Patna",
    dek: "What to check before you travel, how to find route numbers, and where to share feedback.",
    section: "bihar",
    tags: ["Transport", "Commuting"],
    location: "Patna",
    desk: "regional",
    mins: 1020,
    format: "explainer",
    image: ["bihar-rail", "Illustration of converging tracks"],
    priority: 54,
  }),
  // ---------------------------------------------------------------- ODISHA
  article({
    slug: "coastal-districts-rehearse-cyclone-drills",
    title: "Odisha's coastal districts rehearse cyclone preparedness drills",
    dek: "Shelter management, early warnings and evacuation routes are tested with local volunteers and panchayat teams.",
    section: "odisha",
    tags: ["Cyclone", "Disaster preparedness"],
    location: "Bhubaneswar",
    desk: "regional",
    mins: 200,
    image: ["odisha-coast", "Illustration of a coastline"],
    priority: 74,
  }),
  article({
    slug: "handloom-clusters-look-to-younger-weavers",
    title: "Odisha's handloom clusters look to a younger generation of weavers",
    dek: "Weaving families say design training and fair prices matter more than subsidies in keeping young people at the loom.",
    section: "odisha",
    topics: ["business"],
    tags: ["Handloom", "Livelihoods"],
    location: "Cuttack",
    desk: "regional",
    mins: 760,
    image: ["odisha-culture", "Abstract illustration of patterns"],
    priority: 58,
  }),
  // ---------------------------------------------------------------- WEST BENGAL
  article({
    slug: "weekend-markets-draw-crowds-before-festive-season",
    title: "Bengal's weekend markets draw crowds as the festive season nears",
    dek: "Stallholders report brisk sales of clothes and household goods, while shoppers compare prices across neighbourhood markets.",
    section: "west-bengal",
    topics: ["business"],
    tags: ["Markets", "Festivals"],
    location: "Kolkata",
    desk: "regional",
    mins: 300,
    image: ["bengal-market", "Illustration of market stalls"],
    priority: 66,
  }),
  article({
    slug: "industrial-belt-eyes-skilling-programmes",
    title: "Asansol–Durgapur industrial belt eyes new skilling programmes",
    dek: "Training institutes and employers are discussing short courses matched to the skills local units say they cannot find.",
    section: "west-bengal",
    topics: ["business"],
    tags: ["Skills", "Industry"],
    location: "Durgapur",
    desk: "regional",
    mins: 980,
    image: ["business-industry", "Illustration of industrial buildings"],
    priority: 56,
  }),
  article({
    slug: "city-heritage-walks-grow-in-popularity",
    title: "Heritage walks grow in popularity across Kolkata's old neighbourhoods",
    dek: "Local guides say more young residents are signing up to learn the history of streets they pass every day.",
    section: "west-bengal",
    topics: ["entertainment"],
    tags: ["Heritage", "Culture"],
    location: "Kolkata",
    desk: "regional",
    mins: 1400,
    image: ["bengal-city", "Illustration of an old city skyline"],
    priority: 53,
  }),
  // ---------------------------------------------------------------- UTTAR PRADESH
  article({
    slug: "expressway-towns-plan-logistics-parks",
    title: "Towns along Uttar Pradesh's expressway corridors plan logistics parks",
    dek: "Local traders hope warehouses and truck terminals will bring jobs; farmers want clarity on land and access roads.",
    section: "uttar-pradesh",
    topics: ["business"],
    tags: ["Infrastructure", "Logistics"],
    location: "Lucknow",
    desk: "regional",
    mins: 240,
    image: ["up-road", "Illustration of a highway"],
    priority: 69,
  }),
  article({
    slug: "ghats-cleanliness-drive-stepped-up",
    title: "Varanasi steps up cleanliness drive along the ghats",
    dek: "More sanitation teams and waste-collection points are planned for the busiest stretches of the riverfront.",
    section: "uttar-pradesh",
    tags: ["Sanitation", "Tourism"],
    location: "Varanasi",
    desk: "regional",
    mins: 660,
    image: ["up-civic", "Illustration of a civic building"],
    priority: 57,
  }),
  article({
    slug: "students-guide-to-board-exam-season",
    title: "Board exam season: a practical preparation guide for students",
    dek: "Teachers share how to plan revision, handle sample papers and look after sleep and health in the final weeks.",
    section: "uttar-pradesh",
    topics: ["education"],
    tags: ["Exams", "Students"],
    location: "Lucknow",
    desk: "explainers",
    mins: 1250,
    format: "explainer",
    image: ["education-books", "Illustration of books"],
    priority: 52,
  }),
  // ---------------------------------------------------------------- INDIA
  article({
    slug: "explained-rail-timetable-changes-eastern-india",
    title: "Explained: what rail timetable revisions mean for daily travellers in eastern India",
    dek: "Changed departure times, new halts and merged services — a step-by-step guide to checking how your regular train is affected.",
    section: "india",
    tags: ["Railways", "Explainer"],
    desk: "explainers",
    mins: 140,
    format: "explainer",
    image: ["india-rail", "Illustration of railway lines"],
    priority: 87,
    takeaways: [
      "Check your train number, not just its name — numbers can change.",
      "Official railway enquiry channels carry the revised timings.",
      "Season-ticket holders should confirm halts at smaller stations.",
    ],
  }),
  article({
    slug: "monsoon-retreat-and-rabi-sowing-explained",
    title: "How the monsoon's retreat shapes the rabi sowing season",
    dek: "Soil moisture, reservoir levels and the timing of the last rains all feed into what farmers plant next. Here is how.",
    section: "india",
    topics: ["business"],
    tags: ["Agriculture", "Monsoon"],
    desk: "explainers",
    mins: 360,
    format: "explainer",
    image: ["india-monsoon", "Illustration of rain clouds over hills"],
    priority: 71,
  }),
  article({
    slug: "digital-payments-in-small-towns",
    title: "Digital payments in small towns: how shopkeepers are adapting",
    dek: "QR codes are now common at kirana counters. Traders talk about what has become easier — and what still worries them.",
    section: "india",
    topics: ["technology", "business"],
    tags: ["Digital payments", "Small business"],
    desk: "national",
    mins: 580,
    image: ["india-tech", "Abstract illustration of circuitry"],
    priority: 65,
  }),
  article({
    slug: "how-a-bill-becomes-law-readers-guide",
    title: "How a bill becomes law: a reader's guide to Parliament",
    dek: "From introduction to presidential assent — the stages every central law passes through, and where citizens can follow along.",
    section: "india",
    topics: ["politics"],
    tags: ["Parliament", "Explainer"],
    desk: "explainers",
    mins: 1600,
    format: "explainer",
    image: ["india-civic", "Illustration of a parliament-style building"],
    priority: 60,
  }),
  // ---------------------------------------------------------------- BUSINESS
  article({
    slug: "small-manufacturers-kolhan-look-to-exports",
    title: "Small manufacturers in the Kolhan region look to exports as input costs ease",
    dek: "Auto-component and fabrication units say steadier raw-material prices give them room to bid for overseas orders.",
    section: "business",
    tags: ["MSME", "Exports", "Manufacturing"],
    location: "Jamshedpur",
    desk: "business",
    mins: 170,
    image: ["business-industry", "Illustration of industrial buildings"],
    priority: 84,
  }),
  article({
    slug: "festive-retail-small-traders-stock-up-early",
    title: "Festive season retail: small traders stock up early",
    dek: "Wholesalers report advance orders for clothing, electronics and sweets as shopkeepers try to avoid last-minute shortages.",
    section: "business",
    tags: ["Retail", "Festivals"],
    location: "Ranchi",
    desk: "business",
    mins: 430,
    image: ["business-market", "Illustration of market stalls"],
    priority: 67,
  }),
  article({
    slug: "msmes-shift-to-digital-invoicing",
    title: "Jharkhand's small businesses and the shift to digital invoicing",
    dek: "Accountants say the switch reduces errors but requires training — especially for family-run firms.",
    section: "business",
    topics: ["technology"],
    tags: ["MSME", "Digital"],
    location: "Dhanbad",
    desk: "business",
    mins: 800,
    image: ["business-chart", "Illustration of a bar chart"],
    priority: 61,
  }),
  article({
    slug: "explained-how-a-gst-return-works-for-a-small-shop",
    title: "Explained: how a GST return works for a small shop",
    dek: "What a monthly or quarterly return contains, the common mistakes, and where small traders can get help.",
    section: "business",
    tags: ["GST", "Explainer"],
    desk: "explainers",
    mins: 1900,
    format: "explainer",
    image: ["business-chart-2", "Illustration of a line chart"],
    priority: 55,
  }),
  article({
    slug: "household-budgets-and-vegetable-prices",
    title: "How vegetable price swings ripple through a household budget",
    dek: "Families describe the trade-offs they make when staples cost more — and the months when it hurts most.",
    section: "business",
    tags: ["Prices", "Household"],
    desk: "business",
    mins: 2300,
    image: ["ranchi-market", "Illustration of a vegetable market"],
    priority: 51,
  }),
  // ---------------------------------------------------------------- SPORTS
  article({
    slug: "young-hockey-players-head-to-national-camp",
    title: "Jharkhand's young hockey players head to national camp after a strong season",
    dek: "Coaches credit school-level leagues and village grounds for a steady pipeline of talent in the state.",
    section: "sports",
    tags: ["Hockey", "Youth sport"],
    location: "Simdega",
    desk: "sports",
    mins: 190,
    image: ["sports-hockey", "Illustration of a sports field"],
    priority: 83,
  }),
  article({
    slug: "district-cricket-league-returns-this-winter",
    title: "District cricket league returns to Jamshedpur's grounds this winter",
    dek: "Clubs are registering squads, and organisers say more matches will be played on weekends to suit working players.",
    section: "sports",
    locality: undefined,
    tags: ["Cricket", "Local sport"],
    location: "Jamshedpur",
    desk: "sports",
    mins: 390,
    image: ["sports-cricket", "Illustration of a cricket ground"],
    priority: 69,
  }),
  article({
    slug: "football-academy-trials-draw-young-players",
    title: "Football academy trials in Ranchi draw young players from across the state",
    dek: "Scouts say they are looking for game intelligence as much as speed, and plan follow-up trials in more districts.",
    section: "sports",
    tags: ["Football", "Youth sport"],
    location: "Ranchi",
    desk: "sports",
    mins: 690,
    image: ["sports-football", "Illustration of a football pitch"],
    priority: 62,
  }),
  article({
    slug: "school-runners-prepare-for-state-meet",
    title: "Athletics: school runners prepare for the state meet",
    dek: "Early-morning sessions on dirt tracks and borrowed spikes — how young athletes train with limited facilities.",
    section: "sports",
    tags: ["Athletics", "Schools"],
    location: "Gumla",
    desk: "sports",
    mins: 1180,
    image: ["sports-athletics", "Illustration of a running track"],
    priority: 56,
  }),
  article({
    slug: "how-village-archery-ranges-produce-talent",
    title: "How village archery ranges in Jharkhand keep producing talent",
    dek: "Coaches and former archers explain the training culture that turns bamboo bows into a path to national competition.",
    section: "sports",
    format: "analysis",
    tags: ["Archery", "Grassroots"],
    location: "Ranchi",
    desk: "sports",
    mins: 2600,
    image: ["jharkhand-hills", "Illustration of hills"],
    priority: 58,
  }),
  // ---------------------------------------------------------------- POLITICS / EDUCATION / HEALTH / ENTERTAINMENT / TECH
  article({
    slug: "explainer-ward-delimitation-in-civic-polls",
    title: "Explainer: how ward delimitation works before civic elections",
    dek: "Why ward boundaries are redrawn, who draws them, and how residents can file objections.",
    section: "politics",
    tags: ["Elections", "Explainer"],
    desk: "explainers",
    mins: 1000,
    format: "explainer",
    image: ["politics-civic", "Illustration of a civic building"],
    priority: 59,
  }),
  article({
    slug: "what-model-code-of-conduct-means-for-voters",
    title: "What the model code of conduct means for voters",
    dek: "The rules that apply to parties and governments once elections are announced — and how to report a violation.",
    section: "politics",
    tags: ["Elections", "Explainer"],
    desk: "explainers",
    mins: 3100,
    format: "explainer",
    image: ["india-civic", "Illustration of a public building"],
    priority: 50,
  }),
  article({
    slug: "scholarship-applications-checklist",
    title: "Scholarship applications: a checklist for students in Jharkhand",
    dek: "Documents to keep ready, common reasons applications are rejected, and how to track your status.",
    section: "education",
    tags: ["Scholarships", "Students"],
    desk: "explainers",
    mins: 1450,
    format: "explainer",
    image: ["jharkhand-classroom", "Illustration of books"],
    priority: 57,
  }),
  article({
    slug: "dengue-season-prevention-steps",
    title: "Dengue season: prevention steps doctors recommend",
    dek: "Emptying standing water, using nets and knowing the warning signs — a practical guide for households.",
    section: "health",
    tags: ["Dengue", "Public health"],
    desk: "explainers",
    mins: 870,
    format: "explainer",
    image: ["health-care", "Abstract illustration representing healthcare"],
    priority: 63,
  }),
  article({
    slug: "regional-film-makers-look-to-streaming",
    title: "Jharkhand's regional film-makers look to streaming for new audiences",
    dek: "Directors working in Nagpuri, Khortha and Santhali say online platforms offer reach that single screens no longer can.",
    section: "entertainment",
    tags: ["Regional cinema", "Streaming"],
    location: "Ranchi",
    desk: "newsroom",
    mins: 1350,
    image: ["entertainment-stage", "Abstract illustration of stage lights"],
    priority: 56,
  }),
  article({
    slug: "folk-music-finds-new-listeners-online",
    title: "Folk music from the region finds new listeners online",
    dek: "Young musicians are recording traditional songs with modern arrangements — and finding audiences far from home.",
    section: "entertainment",
    tags: ["Music", "Culture"],
    desk: "newsroom",
    mins: 2900,
    image: ["odisha-culture", "Abstract illustration of patterns"],
    priority: 50,
  }),
  article({
    slug: "rural-broadband-what-it-could-change",
    title: "Rural broadband: what faster internet could change for Jharkhand's villages",
    dek: "Online classes, telemedicine and government services all depend on connections that remain patchy in many blocks.",
    section: "technology",
    tags: ["Internet", "Rural development"],
    desk: "newsroom",
    mins: 2000,
    format: "analysis",
    image: ["technology-circuit", "Abstract illustration of circuitry"],
    priority: 58,
  }),
];

/**
 * Demo "most read" order. In production this is computed from article_views
 * (see supabase/schema.sql → most_read view). No view counts are shown.
 */
export const demoMostReadOrder = [
  "festival-traffic-plan-for-bistupur-and-sakchi-markets",
  "districts-asked-to-map-flood-prone-villages-before-next-monsoon",
  "traffic-study-recommends-signal-upgrades-at-busy-junctions",
  "explained-rail-timetable-changes-eastern-india",
  "subarnarekha-riverfront-walkway-residents-weigh-in",
  "young-hockey-players-head-to-national-camp",
  "dengue-season-prevention-steps",
  "weekly-haats-see-early-winter-crowds",
];
