/**
 * Central image library.
 *
 * `image-library.json` is generated by scripts/images/fetch-selected.mjs from
 * reviewed Wikimedia Commons selections — licence, author and source are read
 * from the Commons API at download time, never typed by hand. Components
 * never reference image URLs directly; they receive MediaImage objects.
 *
 * Production workflow: newsroom upload → Supabase Storage (`media` bucket) →
 * `media` row (alt, caption, credit, kind, source) → articles.hero_image →
 * the same MediaImage shape → optimised by next/image everywhere.
 */
import type { ImageKind, MediaImage } from "@/lib/types";
import library from "./image-library.json";

export type ImageKey = keyof typeof library;

interface LibraryEntry {
  src: string;
  width: number;
  height: number;
  alt: string;
  caption: string;
  focal?: string;
  source: {
    name: string;
    title: string;
    url: string;
    author: string;
    licence: string;
    licenceUrl: string;
    attributionRequired: boolean;
  };
}

export function creditLine(author: string | undefined, sourceName: string, licence?: string) {
  const who = author && author !== "Unknown" ? `${author} / ${sourceName}` : sourceName;
  return `Photo: ${who}${licence ? ` (${licence})` : ""}`;
}

/**
 * A library photo as a MediaImage. Demo stories use `kind: "representative"`:
 * the photo illustrates the subject, it does not show the (fictional) event.
 */
export function libraryImage(key: ImageKey, kind: ImageKind = "representative"): MediaImage {
  const e = library[key] as LibraryEntry;
  return {
    src: e.src,
    alt: e.alt,
    width: e.width,
    height: e.height,
    caption: e.caption,
    credit: creditLine(e.source.author, e.source.name, e.source.licence),
    kind,
    focal: e.focal,
    source: { ...e.source },
  };
}

export const allLibraryImages = () => (Object.keys(library) as ImageKey[]).map((k) => ({ key: k, ...(library[k] as LibraryEntry) }));

export const imageKindLabel: Record<ImageKind, string | null> = {
  event: null,
  representative: "Representative image",
  file: "File photo",
  illustration: "Illustration",
  "ai-illustration": "AI-generated illustration",
};
